import { NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { siteUrl } from "@/lib/site-url";
import { sendSignInLink } from "@/lib/email/send";
import { limiters, requestIp } from "@/lib/rate-limit";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * "EMAIL ME A SIGN-IN LINK."
 *
 * Most clients never set a password — invite onboarding deliberately never
 * asks for one — so this is their everyday door, not a recovery path.
 *
 * ALWAYS ANSWERS OK. Whether the address has an account or not, the
 * response is the same "check your inbox" — anything else is an oracle for
 * probing which emails are customers.
 *
 * The link is generated by Supabase but sent by us through Resend on the
 * verified domain, targeting our /auth/callback with the token hash so the
 * exchange actually happens (Supabase's own mailer is rate-limited to a
 * couple an hour and arrives unbranded).
 */

type Body = { email?: string };

export async function POST(request: Request) {
  const ip = requestIp(request);
  const ipLimit = await limiters.magicLink.limit(`ml:${ip}`);
  if (!ipLimit.success) {
    return NextResponse.json({ error: "RATE_LIMITED" }, { status: 429 });
  }

  let body: Body;
  try {
    body = (await request.json()) as Body;
  } catch {
    return NextResponse.json({ error: "BAD_REQUEST" }, { status: 400 });
  }

  const email = (body.email ?? "").trim().toLowerCase();
  if (!email || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) {
    return NextResponse.json({ error: "EMAIL_INVALID" }, { status: 400 });
  }

  // Per-address throttle, keyed separately from the IP throttle so one
  // shared office IP can't lock a whole gym out of their accounts.
  const emailLimit = await limiters.magicLink.limit(`ml:${email}`);
  if (!emailLimit.success) {
    return NextResponse.json({ error: "RATE_LIMITED" }, { status: 429 });
  }

  try {
    const sb = supabaseAdmin();
    const link = await sb.auth.admin.generateLink({
      type: "magiclink",
      email,
    });
    const hashed = link.data?.properties?.hashed_token;
    const user = link.data?.user;
    if (hashed && user) {
      const signInUrl = `${siteUrl()}/auth/callback?token_hash=${encodeURIComponent(
        hashed,
      )}&type=magiclink&next=${encodeURIComponent("/app/today")}`;
      const rawFirst =
        String(user.user_metadata?.full_name ?? "").split(/\s+/)[0] ||
        // "kieron.hawke" is not a greeting; take the first word-ish chunk
        // and cap it.
        email.split("@")[0].split(/[\W_]+/)[0];
      const firstName = rawFirst
        ? rawFirst[0].toUpperCase() + rawFirst.slice(1)
        : "there";
      await sendSignInLink({ to: email, firstName, signInUrl }).catch((e) => {
        console.error("[magic-link] send failed", e);
      });
    }
    // Unknown address falls through to the same OK — no oracle.
  } catch (e) {
    // generateLink throws for unknown users on some GoTrue versions;
    // that's the same "no account" case and gets the same answer.
    console.info("[magic-link] no link generated", e instanceof Error ? e.message : e);
  }

  return NextResponse.json({ ok: true });
}
