import { describe, expect, it } from "vitest";
import { STATION_PATHS } from "@/components/export/station-paths";
import { STATION_META, type StationKey } from "@/lib/plan/stations";

/**
 * The pictograms are generated by a tracing script, so what needs testing is
 * not their shape — it is that the generated file is intact and that every
 * kind of work the classifier can return still has something to draw. A key
 * with no glyph renders as a bare dot, which is the failure that made the
 * first two icon sets look unfinished.
 */

const HYROX: StationKey[] = [
  "run",
  "ski",
  "row",
  "sled-push",
  "sled-pull",
  "burpee",
  "farmers",
  "lunges",
  "wall-balls",
];

describe("the traced pictograms", () => {
  it("covers all eight stations plus the run", () => {
    for (const key of HYROX) {
      expect(STATION_PATHS[key], `no pictogram for ${key}`).toBeTruthy();
      expect(STATION_PATHS[key].d.length).toBeGreaterThan(0);
    }
    expect(STATION_PATHS.roxzone).toBeTruthy();
  });

  it("every path is a closed, well-formed subpath", () => {
    for (const [name, entry] of Object.entries(STATION_PATHS)) {
      for (const d of entry.d) {
        expect(d.startsWith("M"), `${name}: does not start with a moveto`).toBe(true);
        expect(d.endsWith("Z"), `${name}: is not closed`).toBe(true);
        // Only the commands the tracer emits. Anything else is corruption.
        expect(d.replace(/[-\d. ]/g, ""), `${name}: unexpected commands`).toBe("MZ");
      }
    }
  });

  it("every coordinate sits inside the 24-unit box", () => {
    // A path that escapes the viewBox is clipped, which looks like a broken
    // icon rather than a bad number.
    for (const [name, entry] of Object.entries(STATION_PATHS)) {
      for (const d of entry.d) {
        for (const n of d.slice(1, -1).trim().split(/\s+/).map(Number)) {
          expect(Number.isFinite(n), `${name}: non-numeric coordinate`).toBe(true);
          expect(n, `${name}: ${n} is outside 0-24`).toBeGreaterThanOrEqual(-0.05);
          expect(n, `${name}: ${n} is outside 0-24`).toBeLessThanOrEqual(24.05);
        }
      }
    }
  });

  it("records where each one came from", () => {
    // Provenance matters here: these are traced from a third party's report.
    for (const [name, entry] of Object.entries(STATION_PATHS)) {
      expect(entry.source, `${name} has no source size`).toMatch(/^\d+x\d+$/);
    }
  });

  it("leaves no station kind without a glyph", () => {
    // Every key the classifier can return is either traced or drawn.
    const drawn = new Set(["bike", "strength", "core", "warmup", "cooldown", "rest", "other"]);
    for (const key of Object.keys(STATION_META) as StationKey[]) {
      const covered = Boolean(STATION_PATHS[key]) || drawn.has(key);
      expect(covered, `${key} has neither a traced nor a drawn glyph`).toBe(true);
    }
  });
});
